### ISSUE TITLE
Error handler for .env not found

### ISSUE THREAD

**Issue by muhsatrio** [Izzur/mail-relay#4]
Hi @Izzur, i want to give a suggestion for this line

https://github.com/Izzur/mail-relay/blob/9b8eb02ab041b4954f3e500a4d915fb4e6a2d0ed/main.go#L27

After print log `.env not found`, I think would be better to type `log.Fatalln()` instead of `log.Prinltn()` because if just `log.Println()`, the program would still running

As the reference: [https://golang.org/pkg/log/#Logger.Fatalln](https://golang.org/pkg/log/#Logger.Fatalln)

Thank you!

**Comment by Izzur** [comment]
@muhsatrio I'm agree with you its better to use `log.Fatalln` but not on condition when .env file not found, because when running on container like docker/k8s its more common to not use .env file

So if required variable (`HOST`, `PASSWORD`, etc) is not found in system environment, use `log.Fatalln` to stop process with exit code 1

**Comment by muhsatrio** [comment]
Ooo I see, I didn't know before about that thing. So it's okay! @Izzur

**Comment by muhsatrio** [comment]
Had submitted #5 as explained by you as enhanchement above, please check @Izzur, thank you!
